### ISSUE TITLE
constrains 

### ISSUE THREAD

**Issue by samek** [crate/crate-mesos-framework#69]
Is there a way to add constrains on which hosts crate can be launched ?

**Comment by chaudum** [comment]
hi @samek 

the framework enforces the contraint that there is only one Crate instance running on each host.
other then that, the only "real" constraint is the ports (which need to be added to the resources, e.g. `--resources=ports(*)[..., 4200-4399]` (see: https://github.com/crate/crate-mesos-framework#ports)
there is also a "soft" constraint defined by the data path. the slaves will still be offered, but Crate will not be installed if the data directory is not present (see: https://github.com/crate/crate-mesos-framework#data-path)

hope I could help

**Comment by samek** [comment]
@chaudum I was thinking more about some custom constraints / attributes of mesos-slave's

Like in my cluster I have environment tag which can be live/devel and I would like to run it on live servers for example or I have couple of slaves with SSD which are tagged that they do have it.

**Comment by chaudum** [comment]
@samek 
I'm sorry, but the Crate framework does not support such custom constraints yet.
